---

extends: default

rules:
  comments:
    min-spaces-from-content: 1
    require-starting-space: true

  comments-indentation: {}

  document-start:
    ignore: |
      .github/**/*.yml

  indentation:
    spaces: consistent
    indent-sequences: consistent

  line-length: disable
